services:
  #  meetnow-server:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    ports:
  #      - 8080:8080
  #    environment:
  #      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
  #      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
  #      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
  #      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
  #      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID}
  #      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET}
  #      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID}
  #      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET}
  #      - CLOUD_AWS_CREDENTIALS_ACCESS_KEY=${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
  #      - CLOUD_AWS_CREDENTIALS_SECRET_KEY=${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
  #    env_file:
  #      - .env
  #    depends_on:
  #      meetnow-db:
  #        condition: service_healthy
  #      meetnow-redis:
  #        condition: service_healthy

  meetnow-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: meetnow
    ports:
      - 3340:3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--password=1234" ]
      interval: 5s
      retries: 10
      timeout: 60s

  meetnow-redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping", "--silent"]
      interval: 5s
      retries: 10

  ngrinder-controller:
    image: ngrinder/controller:3.5
    container_name: ngrinder-controller
    ports:
      - "8081:8080"  # UI 접속용
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - meetnow-server
    networks:
      - default

  ngrinder-agent:
    image: ngrinder/agent:3.5
    container_name: ngrinder-agent
    environment:
      - CONTROLLER_HOST=ngrinder-controller
      - TZ=Asia/Seoul
    depends_on:
      - ngrinder-controller
    networks:
      - default

volumes:
  mysql-data: